export const USER_DETAILS = 'USER_DETAILS';
export const SET_USER_DETAILS_LOCATIONS = 'SET_USER_DETAILS_LOCATIONS';
export const SET_USER_DETAILS_GENDERS = 'SET_USER_DETAILS_GENDERS';
export const SET_USER_DETAILS_MARITAL_STATUSES = 'SET_USER_DETAILS_MARITAL_STATUSES';