export const SET_SHOPPING_LISTS = 'SET_SHOPPING_LISTS';
export const ADD_SHOPPING_LIST = 'ADD_SHOPPING_LIST';
export const UPDATE_SHOPPING_LIST = 'UPDATE_SHOPPING_LIST';
export const DELETE_SHOPPING_LIST = 'DELETE_SHOPPING_LIST';
export const ADD_SHOPPING_LIST_ITEM = 'ADD_SHOPPING_LIST_ITEM';
export const SET_SHOPPING_LIST_UNITS = 'SET_SHOPPING_LIST_UNITS';
