export const SET_FEATURED_PRODUCTS = 'SET_FEATURED_PRODUCTS';
export const SET_RATED_PRODUCTS = 'SET_RATED_PRODUCTS';
export const SET_PRODUCT_RATING_CATEGORIES = 'SET_PRODUCT_RATING_CATEGORIES';
export const SET_CATEGORY_PRODUCTS = 'SET_CATEGORY_PRODUCTS';
export const SET_CATEGORY_SUBCATEGORIES = 'SET_CATEGORY_SUBCATEGORIES';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
